### ISSUE TITLE
Bugfix: parsing text/plain attachments

### ISSUE THREAD

**Issue by naidishuli** [mnako/letters#41]
When an email contain a text/plain attachments it will not parse it as though, instead the parser will treat as normal text and will put the data in the text body of the email. I suppose the same will happen for text/html files also.

In the parsePart function on parsers.go file it checks the content type and only if it doesn't match any of the conditional content types it will treat it as an attachment. I think that it should check if we're dealing with an attachment first before moving forward with the other checks. I did a code fix locally with testing also, but can't push to a new branch to create a PR for it.

**Comment by mnako** [comment]
@naidishuli,

Thank you for opening the issue.

I am not entirely sure I understand the issue you are describing, as it seems to be a combination of a non-multipart message that still has attachments.

If you could provide an example of such a message, I would be happy to look into it.

**Comment by mnako** [comment]
@naidishuli, thank you for providing the example. This helps a lot. If I now understand correctly, we are dealing with an attached file in a multipart/alternative content-type.

I will look into this issue shortly.

**Comment by mnako** [comment]
@naidishuli, thank you for taking the time to report this issue. The problem should now be solved in https://github.com/mnako/letters/releases/tag/v0.2.0.
